version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-local-java-quarkus
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-local-java-quarkus-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - eventuate-local-java-quarkus-
      - run: TERM=dumb ./gradlew testClasses aggregateJavaDocs
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-local-java-quarkus-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all.sh
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./scripts/deploy-artifacts.sh
          when: on_success
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
